title: Developer
email: rena@wiznet.io
description: Rena blog
author: rena
baseurl: "/"
url: "https://renakim.github.io"

# Social Profiles
twitter_username: chalsu_
github_username: renakim
# facebook_username: kyi8907

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
