title: Developer
email: rena@wiznet.io
description: story
author: rena
baseurl: "/"
url: "https://renakim.github.io"

# comments
disqusShortname: "renablog"

# disqus
# discus-identifier: "renablog"

# Social Profiles
github_username: renakim

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/posts/page:num/"
permalink: "/:year/:month/:day/:title/"
plugins:
  - jekyll-feed
  - jekyll-paginate

encoding: utf-8
