# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
# relative_permalinks: true

# Setup
title: Developer
tagline: ":)"
description: "Developer Story"
url: https://renakim.github.io
baseurl: "/"
paginate: 3

# Comments
comments:
  provider: disqus
disqus:
  shortname: renablog

category_dir: category/
tag_dir: tag/

# About/contact
author:
  name: Rena Kim
  url: https://renakim.github.io
  email: rena@wiznet.io

# Social Profiles
github_username: renakim

plugins:
  - jekyll-paginate

# Custom vars
version: 1.0.1
