baseurl = "https://renakim.github.io/"
title: Developer
canonifyurls = true
paginate = 6
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."
#googleAnalytics = "UA-123-45" # delete or comment to disable Google Analytics JS generation
disqusShortname = "renablog" #delete or comment to disable Disqus comments

[author]
  name = "rena"
